export default [
    { code: "AF", name: "Afghanistan", emoji: "🇦🇫" },
    { code: "AO", name: "Angola", emoji: "🇦🇴" },
    { code: "AL", name: "Albania", emoji: "🇦🇱" },
    { code: "AD", name: "Andorra", emoji: "🇦🇩" },
    { code: "AE", name: "United Arab Emirates", emoji: "🇦🇪" },
    { code: "AR", name: "Argentina", emoji: "🇦🇷" },
    { code: "AM", name: "Armenia", emoji: "🇦🇲" },
    { code: "AG", name: "Antigua and Barbuda", emoji: "🇦🇬" },
    { code: "AU", name: "Australia", emoji: "🇦🇺" },
    { code: "AT", name: "Austria", emoji: "🇦🇹" },
    { code: "AZ", name: "Azerbaijan", emoji: "🇦🇿" },
    { code: "BI", name: "Burundi", emoji: "🇧🇮" },
    { code: "BE", name: "Belgium", emoji: "🇧🇪" },
    { code: "BJ", name: "Benin", emoji: "🇧🇯" },
    { code: "BF", name: "Burkina Faso", emoji: "🇧🇫" },
    { code: "BD", name: "Bangladesh", emoji: "🇧🇩" },
    { code: "BG", name: "Bulgaria", emoji: "🇧🇬" },
    { code: "BH", name: "Bahrain", emoji: "🇧🇭" },
    { code: "BS", name: "Bahamas", emoji: "🇧🇸" },
    { code: "BA", name: "Bosnia and Herzegovina", emoji: "🇧🇦" },
    { code: "BY", name: "Belarus", emoji: "🇧🇾" },
    { code: "BZ", name: "Belize", emoji: "🇧🇿" },
    { code: "BO", name: "Bolivia", emoji: "🇧🇴" },
    { code: "BR", name: "Brazil", emoji: "🇧🇷" },
    { code: "BB", name: "Barbados", emoji: "🇧🇧" },
    { code: "BN", name: "Brunei", emoji: "🇧🇳" },
    { code: "BT", name: "Bhutan", emoji: "🇧🇹" },
    { code: "BW", name: "Botswana", emoji: "🇧🇼" },
    { code: "CF", name: "Central African Republic", emoji: "🇨🇫" },
    { code: "CA", name: "Canada", emoji: "🇨🇦" },
    { code: "CH", name: "Switzerland", emoji: "🇨🇭" },
    { code: "CL", name: "Chile", emoji: "🇨🇱" },
    { code: "CN", name: "China", emoji: "🇨🇳" },
    { code: "CI", name: "Ivory Coast", emoji: "🇨🇮" },
    { code: "CM", name: "Cameroon", emoji: "🇨🇲" },
    { code: "CD", name: "DR Congo", emoji: "🇨🇩" },
    { code: "CG", name: "Republic of the Congo", emoji: "🇨🇬" },
    { code: "CO", name: "Colombia", emoji: "🇨🇴" },
    { code: "KM", name: "Comoros", emoji: "🇰🇲" },
    { code: "CV", name: "Cape Verde", emoji: "🇨🇻" },
    { code: "CR", name: "Costa Rica", emoji: "🇨🇷" },
    { code: "CU", name: "Cuba", emoji: "🇨🇺" },
    { code: "CY", name: "Cyprus", emoji: "🇨🇾" },
    { code: "CZ", name: "Czechia", emoji: "🇨🇿" },
    { code: "DE", name: "Germany", emoji: "🇩🇪" },
    { code: "DJ", name: "Djibouti", emoji: "🇩🇯" },
    { code: "DM", name: "Dominica", emoji: "🇩🇲" },
    { code: "DK", name: "Denmark", emoji: "🇩🇰" },
    { code: "DO", name: "Dominican Republic", emoji: "🇩🇴" },
    { code: "DZ", name: "Algeria", emoji: "🇩🇿" },
    { code: "EC", name: "Ecuador", emoji: "🇪🇨" },
    { code: "EG", name: "Egypt", emoji: "🇪🇬" },
    { code: "ER", name: "Eritrea", emoji: "🇪🇷" },
    { code: "ES", name: "Spain", emoji: "🇪🇸" },
    { code: "EE", name: "Estonia", emoji: "🇪🇪" },
    { code: "ET", name: "Ethiopia", emoji: "🇪🇹" },
    { code: "FI", name: "Finland", emoji: "🇫🇮" },
    { code: "FJ", name: "Fiji", emoji: "🇫🇯" },
    { code: "FR", name: "France", emoji: "🇫🇷" },
    { code: "FM", name: "Micronesia", emoji: "🇫🇲" },
    { code: "GA", name: "Gabon", emoji: "🇬🇦" },
    { code: "GB", name: "United Kingdom", emoji: "🇬🇧" },
    { code: "GE", name: "Georgia", emoji: "🇬🇪" },
    { code: "GH", name: "Ghana", emoji: "🇬🇭" },
    { code: "GN", name: "Guinea", emoji: "🇬🇳" },
    { code: "GM", name: "Gambia", emoji: "🇬🇲" },
    { code: "GW", name: "Guinea-Bissau", emoji: "🇬🇼" },
    { code: "GQ", name: "Equatorial Guinea", emoji: "🇬🇶" },
    { code: "GR", name: "Greece", emoji: "🇬🇷" },
    { code: "GD", name: "Grenada", emoji: "🇬🇩" },
    { code: "GT", name: "Guatemala", emoji: "🇬🇹" },
    { code: "GY", name: "Guyana", emoji: "🇬🇾" },
    { code: "HN", name: "Honduras", emoji: "🇭🇳" },
    { code: "HR", name: "Croatia", emoji: "🇭🇷" },
    { code: "HT", name: "Haiti", emoji: "🇭🇹" },
    { code: "HU", name: "Hungary", emoji: "🇭🇺" },
    { code: "ID", name: "Indonesia", emoji: "🇮🇩" },
    { code: "IN", name: "India", emoji: "🇮🇳" },
    { code: "IE", name: "Ireland", emoji: "🇮🇪" },
    { code: "IR", name: "Iran", emoji: "🇮🇷" },
    { code: "IQ", name: "Iraq", emoji: "🇮🇶" },
    { code: "IS", name: "Iceland", emoji: "🇮🇸" },
    { code: "IL", name: "Israel", emoji: "🇮🇱" },
    { code: "IT", name: "Italy", emoji: "🇮🇹" },
    { code: "JM", name: "Jamaica", emoji: "🇯🇲" },
    { code: "JO", name: "Jordan", emoji: "🇯🇴" },
    { code: "JP", name: "Japan", emoji: "🇯🇵" },
    { code: "KZ", name: "Kazakhstan", emoji: "🇰🇿" },
    { code: "KE", name: "Kenya", emoji: "🇰🇪" },
    { code: "KG", name: "Kyrgyzstan", emoji: "🇰🇬" },
    { code: "KH", name: "Cambodia", emoji: "🇰🇭" },
    { code: "KI", name: "Kiribati", emoji: "🇰🇮" },
    { code: "KN", name: "Saint Kitts and Nevis", emoji: "🇰🇳" },
    { code: "KR", name: "South Korea", emoji: "🇰🇷" },
    { code: "KW", name: "Kuwait", emoji: "🇰🇼" },
    { code: "LA", name: "Laos", emoji: "🇱🇦" },
    { code: "LB", name: "Lebanon", emoji: "🇱🇧" },
    { code: "LR", name: "Liberia", emoji: "🇱🇷" },
    { code: "LY", name: "Libya", emoji: "🇱🇾" },
    { code: "LC", name: "Saint Lucia", emoji: "🇱🇨" },
    { code: "LI", name: "Liechtenstein", emoji: "🇱🇮" },
    { code: "LK", name: "Sri Lanka", emoji: "🇱🇰" },
    { code: "LS", name: "Lesotho", emoji: "🇱🇸" },
    { code: "LT", name: "Lithuania", emoji: "🇱🇹" },
    { code: "LU", name: "Luxembourg", emoji: "🇱🇺" },
    { code: "LV", name: "Latvia", emoji: "🇱🇻" },
    { code: "MA", name: "Morocco", emoji: "🇲🇦" },
    { code: "MC", name: "Monaco", emoji: "🇲🇨" },
    { code: "MD", name: "Moldova", emoji: "🇲🇩" },
    { code: "MG", name: "Madagascar", emoji: "🇲🇬" },
    { code: "MV", name: "Maldives", emoji: "🇲🇻" },
    { code: "MX", name: "Mexico", emoji: "🇲🇽" },
    { code: "MH", name: "Marshall Islands", emoji: "🇲🇭" },
    { code: "MK", name: "Macedonia", emoji: "🇲🇰" },
    { code: "ML", name: "Mali", emoji: "🇲🇱" },
    { code: "MT", name: "Malta", emoji: "🇲🇹" },
    { code: "MM", name: "Myanmar", emoji: "🇲🇲" },
    { code: "ME", name: "Montenegro", emoji: "🇲🇪" },
    { code: "MN", name: "Mongolia", emoji: "🇲🇳" },
    { code: "MZ", name: "Mozambique", emoji: "🇲🇿" },
    { code: "MR", name: "Mauritania", emoji: "🇲🇷" },
    { code: "MU", name: "Mauritius", emoji: "🇲🇺" },
    { code: "MW", name: "Malawi", emoji: "🇲🇼" },
    { code: "MY", name: "Malaysia", emoji: "🇲🇾" },
    { code: "NA", name: "Namibia", emoji: "🇳🇦" },
    { code: "NE", name: "Niger", emoji: "🇳🇪" },
    { code: "NG", name: "Nigeria", emoji: "🇳🇬" },
    { code: "NI", name: "Nicaragua", emoji: "🇳🇮" },
    { code: "NL", name: "Netherlands", emoji: "🇳🇱" },
    { code: "NO", name: "Norway", emoji: "🇳🇴" },
    { code: "NP", name: "Nepal", emoji: "🇳🇵" },
    { code: "NR", name: "Nauru", emoji: "🇳🇷" },
    { code: "NZ", name: "New Zealand", emoji: "🇳🇿" },
    { code: "OM", name: "Oman", emoji: "🇴🇲" },
    { code: "PK", name: "Pakistan", emoji: "🇵🇰" },
    { code: "PA", name: "Panama", emoji: "🇵🇦" },
    { code: "PE", name: "Peru", emoji: "🇵🇪" },
    { code: "PH", name: "Philippines", emoji: "🇵🇭" },
    { code: "PW", name: "Palau", emoji: "🇵🇼" },
    { code: "PG", name: "Papua New Guinea", emoji: "🇵🇬" },
    { code: "PL", name: "Poland", emoji: "🇵🇱" },
    { code: "KP", name: "North Korea", emoji: "🇰🇵" },
    { code: "PT", name: "Portugal", emoji: "🇵🇹" },
    { code: "PY", name: "Paraguay", emoji: "🇵🇾" },
    { code: "QA", name: "Qatar", emoji: "🇶🇦" },
    { code: "RO", name: "Romania", emoji: "🇷🇴" },
    { code: "RU", name: "Russia", emoji: "🇷🇺" },
    { code: "RW", name: "Rwanda", emoji: "🇷🇼" },
    { code: "SA", name: "Saudi Arabia", emoji: "🇸🇦" },
    { code: "SD", name: "Sudan", emoji: "🇸🇩" },
    { code: "SN", name: "Senegal", emoji: "🇸🇳" },
    { code: "SG", name: "Singapore", emoji: "🇸🇬" },
    { code: "SB", name: "Solomon Islands", emoji: "🇸🇧" },
    { code: "SL", name: "Sierra Leone", emoji: "🇸🇱" },
    { code: "SV", name: "El Salvador", emoji: "🇸🇻" },
    { code: "SM", name: "San Marino", emoji: "🇸🇲" },
    { code: "SO", name: "Somalia", emoji: "🇸🇴" },
    { code: "RS", name: "Serbia", emoji: "🇷🇸" },
    { code: "SS", name: "South Sudan", emoji: "🇸🇸" },
    { code: "ST", name: "São Tomé and Príncipe", emoji: "🇸🇹" },
    { code: "SR", name: "Suriname", emoji: "🇸🇷" },
    { code: "SK", name: "Slovakia", emoji: "🇸🇰" },
    { code: "SI", name: "Slovenia", emoji: "🇸🇮" },
    { code: "SE", name: "Sweden", emoji: "🇸🇪" },
    { code: "SZ", name: "Swaziland", emoji: "🇸🇿" },
    { code: "SC", name: "Seychelles", emoji: "🇸🇨" },
    { code: "SY", name: "Syria", emoji: "🇸🇾" },
    { code: "TD", name: "Chad", emoji: "🇹🇩" },
    { code: "TG", name: "Togo", emoji: "🇹🇬" },
    { code: "TH", name: "Thailand", emoji: "🇹🇭" },
    { code: "TJ", name: "Tajikistan", emoji: "🇹🇯" },
    { code: "TM", name: "Turkmenistan", emoji: "🇹🇲" },
    { code: "TL", name: "Timor-Leste", emoji: "🇹🇱" },
    { code: "TO", name: "Tonga", emoji: "🇹🇴" },
    { code: "TT", name: "Trinidad and Tobago", emoji: "🇹🇹" },
    { code: "TN", name: "Tunisia", emoji: "🇹🇳" },
    { code: "TR", name: "Turkey", emoji: "🇹🇷" },
    { code: "TV", name: "Tuvalu", emoji: "🇹🇻" },
    { code: "TZ", name: "Tanzania", emoji: "🇹🇿" },
    { code: "UG", name: "Uganda", emoji: "🇺🇬" },
    { code: "UA", name: "Ukraine", emoji: "🇺🇦" },
    { code: "UY", name: "Uruguay", emoji: "🇺🇾" },
    { code: "US", name: "United States", emoji: "🇺🇸" },
    { code: "UZ", name: "Uzbekistan", emoji: "🇺🇿" },
    { code: "VA", name: "Vatican City", emoji: "🇻🇦" },
    { code: "VC", name: "Saint Vincent and the Grenadines", emoji: "🇻🇨" },
    { code: "VE", name: "Venezuela", emoji: "🇻🇪" },
    { code: "VN", name: "Vietnam", emoji: "🇻🇳" },
    { code: "VU", name: "Vanuatu", emoji: "🇻🇺" },
    { code: "WS", name: "Samoa", emoji: "🇼🇸" },
    { code: "YE", name: "Yemen", emoji: "🇾🇪" },
    { code: "ZA", name: "South Africa", emoji: "🇿🇦" },
    { code: "ZM", name: "Zambia", emoji: "🇿🇲" },
    { code: "ZW", name: "Zimbabwe", emoji: "🇿🇼" },
];
