export default [
    {
        id: "1",
        name: "Bird Watching Experience",
        seller: { id: "1" },
        photo: { src: "https://placeimg.com/140/105/animals" },
    },
    {
        id: "2",
        name: "1 Hour deep dive Scuba diving",
        seller: { id: "2" },
        photo: { src: "https://placeimg.com/140/105/nature" },
    },
    {
        id: "3",
        name: "Paragliding Experience",
        seller: { id: "1" },
        photo: { src: "https://placeimg.com/140/105/nature" },
    },
    {
        id: "4",
        name: "Art n Architecture Tour",
        seller: { id: "2" },
        photo: { src: "https://placeimg.com/140/105/arch" },
    },
    {
        id: "5",
        name: "1 Hour Football Training",
        seller: { id: "1" },
        photo: { src: "https://placeimg.com/140/105/people" },
    },
    {
        id: "6",
        name: "New Delhi Virtual Tour",
        seller: { id: "3" },
        photo: { src: "https://placeimg.com/140/105/arch" },
    },
    {
        id: "7",
        name: "3 Hour Jungle Safari",
        seller: { id: "1" },
        photo: { src: "https://placeimg.com/140/105/animals" },
    },
    {
        id: "8",
        name: "Nile River Boating Experience",
        seller: { id: "2" },
        photo: { src: "https://placeimg.com/140/105/arch" },
    },
    {
        id: "9",
        name: "Bangalore Virtual Tour",
        seller: { id: "3" },
        photo: { src: "https://placeimg.com/140/105/tech" },
    },
    {
        id: "10",
        name: "Rock Climbing Adventure",
        seller: { id: "1" },
        photo: { src: "https://placeimg.com/140/105/people" },
    },
    {
        id: "11",
        name: "New Your Virtual Tour",
        seller: { id: "1" },
        photo: { src: "https://placeimg.com/140/105/arch" },
    },
    {
        id: "12",
        name: "River Rafting Experience",
        seller: { id: "2" },
        photo: { src: "https://placeimg.com/140/105/animals" },
    },
    {
        id: "13",
        name: "2 Hour Football Training",
        seller: { id: "1" },
        photo: { src: "https://placeimg.com/140/105/people" },
    },
    {
        id: "14",
        name: "Himalayas Virtual Tour",
        seller: { id: "3" },
        photo: { src: "https://placeimg.com/140/105/nature" },
    },
];
