#!/bin/bash

export NODE_OPTIONS="--openssl-legacy-provider"

if [[ $1 == "build" ]]; then
  npx build-storybook -s public
else
  # node scripts/prepare
  npx start-storybook -p 6006 -s public --no-open "$@"
fi
